import { getServerSession } from "next-auth";
import "./globals.css";
import { authOptions } from "../../pages/api/auth/[...nextauth]";
import Navbar from "@/components/navbar";
import SessionProvider from "./SessionProvider";
import { Providers } from "./providers";
export const metadata = {
  title: "Kata Academy",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html className="dark" suppressHydrationWarning lang="pt-br">
      <body>
        <SessionProvider session={session}>
          <Providers>
            <Navbar></Navbar>
            {children}
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
